taxi_rides_ny:
  outputs:
    dev:
      dataset: data_engineering_zoomcamp
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-central1
      method: oauth
      priority: interactive
      project: sandbox-402413
      threads: 1
      type: bigquery
  target: dev